# FORCE COMPLETE REDEPLOY: 2025-07-26T15:00:00.000Z - Fixed login authentication and added admin user
services:
  - type: web
    name: tablero-control
    env: node
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 