services:
  - type: web
    name: tablero-control-1
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    branch: main 