services:
  - type: web
    name: tablero-control-1
    env: node
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    healthCheckPath: /health
    autoDeploy: true 